import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { getServerSession } from "next-auth/next";

import { authOptions } from "@/lib/auth";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const session = await getServerSession(authOptions);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Des <a> et non des <Link> : ce sont des routes d'API NextAuth, pas des pages.
            La règle no-html-link-for-pages ne fait pas la différence, d'où les exceptions. */}
        <header className="flex justify-end gap-4 border-b p-4">
          {session ? (
            <>
              <span>{session.user?.name}</span>
              {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
              <a href="/api/auth/signout" className="underline">
                Déconnexion
              </a>
            </>
          ) : (
            <>
              <Link href="/inscription" className="underline">
                Créer un compte
              </Link>
              {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
              <a href="/api/auth/signin" className="underline">
                Connexion
              </a>
            </>
          )}
        </header>
        {children}
      </body>
    </html>
  );
}
